server:
  port: 8011
author:
  nickname: "chenf"
#mybatis配置
mybatis:
  type-aliases-package: com.smart.car.points.entity
  mapper-locations: classpath:mapper/*.xml
  #输出sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  #1.微服务的名称
  application:
    name: smartcar-points
  main:
    allow-bean-definition-overriding: true
  #db连接
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_points?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ke8ke18zai2
  #2.nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 使用sentinel流量控制
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080 #指定sentinel控制台地址
# 释放所有请求接口
management:
  endpoints:
    web:
      exposure:
        include: '*'
#logback配置
logging:
  level:
    root: info
  file:
    name: ./tmp/points.log

