server:
  port: 8004

mybatis:
  type-aliases-package: com.smart.car.message.entity
  mapper-locations: classpath:mapper/*.xml

#logback配置
logging:
  level:
    root: info
    #关闭nacos心跳日志
    com.alibaba.nacos.client.*: WARN
  file:
    name: ./tmp/message.log

spring:
  #stream配置
  stream:
    bindings:
      input: #自定义的通道名，对应代码中的生产监听组
        destination: park-pay-topic   #相当于rocketmq的topic
        content-type: text/plain
        group: park-pay-group    #生产组
    #          consumer:
    #            max-attempts: 1   #失败重试
    rocketmq: #消费者配置
      binder:
        name-server: 127.0.0.1:9876
        enable-msg-trace: true
      bindings:
        input: #自定义通道名
          consumer:
            orderly: true
            #delay-level-when-next-consume: 1 # 异步消费消息模式下消费失败重试策略，默认为 0
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/car_message?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ke8ke18zai2
  #1.微服务的名称
  application:
    name: smartcar-message
  #2.nacos注册中心地址
  cloud:
    #nacos配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#4.actuator开放所有endpoint，配合spring-boot-admin使用，实际生产根据自身需要开放
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#配置Feign超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 10000  #毫秒
        readTimeout: 10000