server:
  port: 8006
author:
  nickname: "chenf"
#mybatis配置
mybatis:
  type-aliases-package: com.smart.car.record.entity
  mapper-locations: classpath:mapper/*.xml
  #输出sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  #stream配置
  stream:
    bindings:
      output:
        destination: park-pay-topic  #指定topic
        content-type: application/json
    rocketmq:
      binder:
        name-server: 127.0.0.1:9876 #rocketmq地址
        enable-msg-trace: true
      bindings:
        output: #自定义通道名
          producer:
            group: park-pay-group-user-ouput #生产者组名
            sync: true    # 是否同步发送消息，默认为 false 异步
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间（毫秒）
    timeout: 1000
    #采用lettuce客户端
    lettuce:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 8
        min-idle: 0
  #1.微服务的名称
  application:
    name: smartcar-record
  main:
    allow-bean-definition-overriding: true
  #db连接
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_record?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ke8ke18zai2
  #2.nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


#logback配置
logging:
  level:
    root: info
  file:
    name: ./tmp/points.log

