server:
  port: 8002

mybatis:
  type-aliases-package: com.smart.car.finance.entity
  mapper-locations: classpath:mapper/*.xml

#logback配置
logging:
  level:
    root: info
    #关闭nacos心跳日志
    com.alibaba.nacos.client.*: WARN
  file:
    name: ./tmp/finance.log

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/car_finance?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ke8ke18zai2
  #1.微服务的名称
  application:
    name: smartcar-finance
  cloud:
    #2.nacos注册中心地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#配置Feign超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 10000  #毫秒
        readTimeout: 10000