server:
  port: 8003
author:
  nickname: "chenf"

#dubbo config
dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: smartcar-carwash #订阅指定服务，逗号分隔
  application:
    qos-enable: false
  #不检测服务提供者是否在线，生产环境建议开启
  config-center:
    check: false


#mybatis配置
mybatis:
  type-aliases-package: com.smart.car.member.entity
  mapper-locations: classpath:mapper/*.xml
  #输出sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  main:
    allow-bean-definition-overriding: true
  #1.微服务的名称
  application:
    name: smartcar-member
  #db连接
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_member?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ke8ke18zai2
#2.nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 使用sentinel流量控制
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719 #如被占用会自动+1
      eager: true  #取消延迟加载
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            namespace: smartcar-member
            data-type: json
            rule-type: flow

# 释放所有请求接口
management:
  endpoints:
    web:
      exposure:
        include: '*'
#logback配置
logging:
  level:
    root: info
  file:
    name: ./tmp/member.log

# feign和ribbon结合，指定策略为Ribbon的随机策略
smartcar-points:
  ribbon:
    NFLoadBalancerRuleClassName: com.smart.car.member.rule.NacosWeightedRule

#1.降级方案一，采用hystrix
feign:
  hystrix:
    enabled: false
  sentinel:
      enabled: true