
server:
  port: 8003
author:
  nickname: "chenf"
#mybatis配置
mybatis:
  type-aliases-package: com.smart.car.member.entity
  mapper-locations: classpath:mapper/*.xml
  #输出sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  #1.微服务的名称
  application:
    name: smartcar-member
  main:
    allow-bean-definition-overriding: true
  #db连接
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_member?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ke8ke18zai2
